import * as Icons from './SIIcons';

export const skillsData = [
  { name: 'TypeScript', icon: Icons.TSIcon },
  { name: 'JavaScript', icon: Icons.JSIcon },
  { name: 'React', icon: Icons.ReactIcon },
  { name: 'Angular', icon: Icons.AngularIcon },
  { name: 'HTML/CSS', icon: Icons.HTMLIcon },
  // { name: 'CSS', icon: Icons.CSSIcon },
  { name: 'Sass (SCSS)', icon: Icons.SassIcon },
  { name: 'Vite', icon: Icons.ViteIcon },
  { name: 'TailwindCSS', icon: Icons.TailwindIcon },
  { name: 'Bulma', icon: Icons.BulmaIcon },
  { name: 'Chakra UI', icon: Icons.ChakraIcon },
  { name: 'Python', icon: Icons.PythonIcon },
  { name: 'Java', icon: Icons.JavaIcon },
  { name: 'C#', icon: Icons.CSharpIcon },
  { name: 'C++', icon: Icons.CPPIcon },
  { name: 'C', icon: Icons.CIcon },
  { name: 'NestJS', icon: Icons.NestJSIcon },
  { name: 'PostgreSQL', icon: Icons.PostgresIcon },
  { name: 'Git', icon: Icons.GitIcon },
  { name: 'Netlify', icon: Icons.NetlifyIcon },
  { name: 'CI/CD', icon: Icons.CICDIcon },
  { name: 'Figma', icon: Icons.FigmaIcon },
  { name: 'Notion', icon: Icons.NotionIcon },
  { name: 'Jira', icon: Icons.JiraIcon },
  { name: 'Unity', icon: Icons.UnityIcon },
  { name: 'Blender', icon: Icons.BlenderIcon },
];

export const interestsData = [
  { name: 'Web Development', icon: Icons.WebDevIcon },
  { name: 'Game Development', icon: Icons.GameDevIcon },
  { name: '3D Art', icon: Icons.ThreeDArtIcon },
  { name: 'Design', icon: Icons.DesignIcon },
  { name: 'Philosophy', icon: Icons.PhilosophyIcon },
  { name: 'Reading', icon: Icons.ReadingIcon },
  { name: 'Weightlifting', icon: Icons.WeightliftingIcon },
  { name: 'Nature', icon: Icons.NatureIcon },
  { name: 'Cats', icon: Icons.CatIcon },
  { name: 'Italy', icon: Icons.ItalyIcon },
  { name: 'Music Production', icon: Icons.MusicIcon },
  { name: 'Oboe', icon: Icons.OboeIcon },
  { name: 'Saxophone', icon: Icons.SaxIcon },
  { name: 'Piano', icon: Icons.PianoIcon },
];
